### ISSUE TITLE
username and email placeholder does not translate on signUp atForm

### ISSUE THREAD

**Issue by spiotr12** [softwarerero/meteor-accounts-t9n#173]
As in title. It works on signIn but does not work on signUp. Or more precisely the placeholder. Password for instance works fine. See screens:
![2017-01-05_00h57_04](https://cloud.githubusercontent.com/assets/10038964/21663701/237a9ee4-d2e2-11e6-9e43-c251ff143256.png)
![2017-01-05_00h57_11](https://cloud.githubusercontent.com/assets/10038964/21663702/237d8d2a-d2e2-11e6-9485-f4ebf4675173.png)
![2017-01-05_00h57_32](https://cloud.githubusercontent.com/assets/10038964/21663704/237dd514-d2e2-11e6-847e-0090ebfd8003.png)
![2017-01-05_00h57_41](https://cloud.githubusercontent.com/assets/10038964/21663703/237dc736-d2e2-11e6-8742-82f56c5cece6.png)

**Comment by spiotr12** [comment]
This is my code
`const pwdField = AccountsTemplates.removeField('password');
AccountsTemplates.removeField('email');
AccountsTemplates.addFields([
	{
		_id: "username",
		type: "text",
		required: true,
		displayName: "username",
		re: /^[a-zA-Z0-9_-]{5,}$/,
		minLength: 5,
	},
	{
		_id: 'email',
		type: 'email',
		required: true,
		displayName: "email",
		re: /.+@(.+){2,}\.(.+){2,}/,
		errStr: 'Invalid email',
	},
	pwdField
]);`

**Comment by softwarerero** [comment]
I can't see how this code can produce the screens you show. There must be more code. Is `AccountsTemplates` your object or is it from a library?

**Comment by spiotr12** [comment]
It's from library

**Comment by spiotr12** [comment]
There is another missing translation "minimum required length" in help-block
![sketch-1483575408206](https://cloud.githubusercontent.com/assets/10038964/21664088/ab82e9f2-d2e4-11e6-8e63-49d919577450.png)

**Comment by spiotr12** [comment]
Okay 👍

**Comment by spiotr12** [comment]
Hi. So I did as you suggested, I've added missing translations in polish ;) there are two commits for pull request [ [main](https://github.com/softwarerero/meteor-accounts-t9n/pull/174/commits/96622466d32904dde8c20e404625508f9f04a712) and [my typo](https://github.com/softwarerero/meteor-accounts-t9n/pull/174/commits/48993e8f2efa921ff96aec7827c4457e44561479) ](its is my very first one). I hope I've done it correctly.

**Comment by softwarerero** [comment]
Looks good to me, although I don't understand polish. Thanks.

**Comment by spiotr12** [comment]
Not a problem, I'm glad I could help 👍 

Last question: how do I update my project to have these updates in my usage of i9n?

**Comment by softwarerero** [comment]
I just published a new release 1.3.7. If you are on a recent Meteor version you should be able to change that version in package.json and call `meteor npm install`.

**Comment by spiotr12** [comment]
Great, I've updated it to 1.3.7 👍 

However It still does not change the error message.... (I've run `meteor reset` command as well - no luck)
![2017-01-07_18h00_13](https://cloud.githubusercontent.com/assets/10038964/21743870/2fab7ef4-d503-11e6-8f31-a781d14ea349.png)

Any idea?
I think if I declare new keys then I could just override it - walk around
But as we've just added translations this should work right?

*I'm testing only that message right now

Thanks for your help

**Comment by softwarerero** [comment]
Without knowing the source code it is difficult to help.

**Comment by softwarerero** [comment]
Closing this as I have no idea how to help here.
